import { ReactNode } from 'react';

// =================================================================
// CORE TYPES
// =================================================================

export type UserRole = 'admin' | 'reseller' | 'customer' | 'superuser' | 'counter';

export interface User {
  id: string;
  email: string;
  name: string; // Stored in profile table
  role: UserRole; // Stored in profile table (or metadata)
  
  // Added properties to fix TS errors
  phone?: string;
  whatsapp?: string;
  isActive: boolean;
  createdAt: Date;
  updatedAt: Date;
  commissionRate?: number;
  resellerId?: string; // NEW: ID of the reseller who referred this user
  totalSales?: number; // NEW: Total sales generated by this user (for resellers)
}

export interface CustomFont {
  id: string;
  name: string;
  file: string;
}

export interface CustomDesign {
  id: string;
  name: string;
  category: string;
  imageUrl: string;
}

export interface ProductCustomization {
  texts: string[];
  font: string;
  startDesign?: string;
  endDesign?: string;
  previewImage: string;
  svgFile: string;
}

export interface SavedDesignTemplate {
  id: string;
  userId: string;
  name: string;
  productId: string;
  productName: string;
  customization: ProductCustomization;
  createdAt: Date;
  updatedAt: Date;
}

export interface ProductCustomizationOptions {
  fonts: string[];
  startDesigns?: string[];
  endDesigns?: string[];
  maxCharacters: number;
  allowedColors?: string[];
}

export interface ImageSizes {
  small: string; // Low resolution placeholder (e.g., 100px)
  medium: string; // Medium resolution (e.g., 600px)
  large: string; // High resolution (e.g., 1200px)
}

export interface ProductVariant {
  id: string;
  name: string;
  price: number;
  stockQuantity: number;
  attributes: Record<string, string>;
}

export type ProductActionButton = 'customize' | 'quick_add' | 'contact' | 'more_info';

export interface Product {
  id: string;
  name: string;
  sku: string;
  description: string;
  basePrice: number;
  discountedPrice?: number;
  images: ImageSizes[]; // UPDATED: Array of ImageSizes objects
  category: string;
  subcategory?: string;
  stockQuantity: number;
  variants: ProductVariant[];
  customizationOptions: ProductCustomizationOptions;
  printPaths: number;
  isActive: boolean;
  tags: string[];
  createdAt: Date;
  updatedAt: Date;
  actionButtons: ProductActionButton[]; // NEW: Configurable action buttons
  moreInfoContent?: string; // NEW: Content for the 'more_info' popup
  
  // Mock properties for AI bulk creation (not part of final DB schema)
  price?: number;
  stock?: number;
}

export interface CartItem {
  productId: string;
  variantId?: string;
  quantity: number;
  customization: ProductCustomization;
  product: Product;
}

export interface Address {
  id: string;
  fullName: string;
  phone: string;
  street: string;
  city: string;
  state: string;
  zipCode: string;
  country: string;
  isDefault: boolean;
}

export interface OrderItem {
  id: string;
  productId: string;
  variantId?: string;
  quantity: number;
  price: number;
  customization: ProductCustomization;
}

export interface Order {
  id: string;
  customerId: string;
  resellerId?: string;
  status: 'pending' | 'confirmed' | 'processing' | 'shipped' | 'delivered' | 'cancelled';
  items: OrderItem[];
  subtotal: number;
  discountAmount: number;
  taxAmount: number;
  shippingCost: number;
  totalAmount: number;
  paymentMethod: string;
  paymentStatus: 'paid' | 'pending' | 'failed';
  shippingAddress: Address;
  deliveryMethod: string;
  designFiles: string[];
  createdAt: Date;
  updatedAt: Date;
}

export interface PromoCode {
  id: string;
  code: string;
  name: string;
  discountType: 'percentage' | 'fixed';
  discountValue: number;
  minimumOrderValue: number;
  usageLimit: number;
  usedCount: number;
  validFrom: Date;
  validTo: Date;
  isActive: boolean;
  resellerId?: string;
  autoAssignReseller: boolean;
  targetCategory?: string; // NEW: Category this promo code applies to (e.g., 'Apparel', 'all')
  createdAt: Date;
  updatedAt: Date;
}

export interface CommissionRecord {
  id: string;
  orderId: string;
  date: Date;
  saleAmount: number;
  rate: number; // percentage
  commissionEarned: number;
  status: 'pending' | 'paid' | 'cancelled';
}

export interface HeroSlide {
  id: string;
  heading: string;
  subheading: string;
  imageUrl: string; // URL or path to uploaded image
  buttonText: string;
  buttonLink: string;
  isActive: boolean;
  sortOrder: number;
}

export interface ImageAsset {
  id: string;
  name: string;
  url: string; // Original URL
  sizes: ImageSizes; // NEW: Store generated sizes
  type: 'product' | 'hero' | 'other';
  uploadedAt: Date;
}

export interface ContactInfo {
  address: string;
  phone: string;
  email: string;
}

export interface FaqItem {
  id: string;
  question: string;
  answer: string;
  sortOrder: number;
}

export interface StaticPage {
  slug: string; // e.g., 'about', 'shipping'
  title: string;
  content: string; // Markdown or HTML content
  isActive: boolean;
}

// --- LEDGER TYPES ---

export type LedgerEntityType = 'customer' | 'reseller' | 'supplier' | 'other';

export interface LedgerEntity {
  id: string;
  name: string;
  type: LedgerEntityType;
  linkedId: string; 
  contact: string;
}

export type TransactionType = 'we_gave' | 'we_received';
export type TransactionItemType = 'cash' | 'product';

export interface LedgerTransaction {
  id: string;
  entityId: string; // ID of the LedgerEntity
  type: TransactionType;
  itemType: TransactionItemType;
  amount: number; // Positive value. Debit/Credit determined by type.
  details: string;
  // NEW fields for product transactions
  productId?: string;
  productName?: string; 
  quantity?: number;
  purchasePrice?: number; // Cost to us (for product received)
  salePrice?: number; // Price to them (for product given)
  createdAt: Date;
}

// --- OPERATOR TRACKING TYPES ---
export interface OperatorActivity {
  id: string;
  operatorId: string;
  type: 'login' | 'logout' | 'sale';
  timestamp: Date;
  details: string; // e.g., 'Order CP-2024-XXXXX processed'
}