import { ReactNode } from 'react';

// =================================================================
// CORE TYPES
// =================================================================

export type UserRole = 'admin' | 'reseller' | 'customer';

export interface User {
  id: string;
  email: string;
  name: string; // Stored in profile table
  role: UserRole; // Stored in profile table (or metadata)
  
  // Added properties to fix TS errors
  phone?: string;
  whatsapp?: string;
  isActive: boolean;
  createdAt: Date;
  updatedAt: Date;
  commissionRate?: number;
  totalEarnings?: number;
  resellerId?: string; // NEW: ID of the reseller who referred this user
  totalSales?: number; // NEW: Total sales generated by this user (for resellers)
}

export interface CustomFont {
  id: string;
  name: string;
  file: string;
}

export interface CustomDesign {
  id: string;
  name: string;
  category: string;
  imageUrl: string;
}

export interface ProductCustomization {
  texts: string[];
  font: string;
  startDesign?: string;
  endDesign?: string;
  previewImage: string;
  svgFile: string;
}

export interface SavedDesignTemplate {
  id: string;
  userId: string;
  name: string;
  productId: string;
  productName: string;
  customization: ProductCustomization;
  createdAt: Date;
  updatedAt: Date;
}

export interface ProductCustomizationOptions {
  fonts: string[];
  startDesigns?: string[];
  endDesigns?: string[];
  maxCharacters: number;
  allowedColors?: string[];
}

export interface ProductVariant {
  id: string;
  name: string;
  price: number;
  stockQuantity: number;
  attributes: Record<string, string>;
}

export interface Product {
  id: string;
  name: string;
  sku: string;
  description: string;
  basePrice: number;
  discountedPrice?: number;
  images: string[];
  category: string;
  subcategory?: string;
  stockQuantity: number;
  variants: ProductVariant[];
  customizationOptions: ProductCustomizationOptions;
  printPaths: number;
  isActive: boolean;
  tags: string[];
  createdAt: Date;
  updatedAt: Date;
}

export interface CartItem {
  productId: string;
  variantId?: string;
  quantity: number;
  customization: ProductCustomization;
  product: Product;
}

export interface Address {
  id: string;
  fullName: string;
  phone: string;
  street: string;
  city: string;
  state: string;
  zipCode: string;
  country: string;
  isDefault: boolean;
}

export interface OrderItem {
  id: string;
  productId: string;
  variantId?: string;
  quantity: number;
  price: number;
  customization: ProductCustomization;
}

export interface Order {
  id: string;
  customerId: string;
  resellerId?: string;
  status: 'pending' | 'confirmed' | 'processing' | 'shipped' | 'delivered' | 'cancelled';
  items: OrderItem[];
  subtotal: number;
  discountAmount: number;
  taxAmount: number;
  shippingCost: number;
  totalAmount: number;
  paymentMethod: string;
  paymentStatus: 'paid' | 'pending' | 'failed';
  shippingAddress: Address;
  deliveryMethod: string;
  designFiles: string[];
  createdAt: Date;
  updatedAt: Date;
}

export interface PromoCode {
  id: string;
  code: string;
  name: string;
  discountType: 'percentage' | 'fixed';
  discountValue: number;
  minimumOrderValue: number;
  usageLimit: number;
  usedCount: number;
  validFrom: Date;
  validTo: Date;
  isActive: boolean;
  resellerId?: string;
  autoAssignReseller: boolean;
  createdAt: Date;
  updatedAt: Date;
}

export interface CommissionRecord {
  id: string;
  orderId: string;
  date: Date;
  saleAmount: number;
  rate: number; // percentage
  commissionEarned: number;
  status: 'pending' | 'paid' | 'cancelled';
}

export interface HeroSlide {
  id: string;
  heading: string;
  subheading: string;
  imageUrl: string; // URL or path to uploaded image
  buttonText: string;
  buttonLink: string;
  isActive: boolean;
  sortOrder: number;
}

export interface ImageAsset {
  id: string;
  name: string;
  url: string;
  type: 'product' | 'hero' | 'other';
  uploadedAt: Date;
}

export interface ContactInfo {
  address: string;
  phone: string;
  email: string;
}

export interface FaqItem {
  id: string;
  question: string;
  answer: string;
  sortOrder: number;
}

export interface StaticPage {
  slug: string; // e.g., 'about', 'shipping'
  title: string;
  content: string; // Markdown or HTML content
  isActive: boolean;
}